### ISSUE TITLE
图标位置调整

### ISSUE THREAD

**Issue by nie11kun** [jrotty/YoduBGM#2]
请问下如何稍微修改图标位置，因为宽屏下和目前主题的搜索重叠了：
![image](https://user-images.githubusercontent.com/11830603/136577266-8d29bdeb-32ce-4744-9346-6929650c768a.png)

我自己调节了下 css 里的 ymusic top 属性发现没变化。

**Comment by jrotty** [comment]
现在支持在插件设置里手动设置了
